### ISSUE TITLE
Version clarification

### ISSUE THREAD

**Issue by lukecyca** [nouveaupg/NouveauPG-OSX#4]
I found this by searching the App Store, which led me to your website and then to this repo. The version I got from the app store is 1.73 but the latest version in this repo is 1.71. Just wondering what the difference is, and if it would be possible to commit those changes, tag, and post a 1.73 release on github as well.

**An aside**: this project is wonderful! It's simple and self-contained and exactly something I can recommend to others, especially who are less willing to fiddle around with multiple utilities and cli programs. Both GPGTools and Keybase.io have become quite large in scope and I've struggled to get non-technical folks comfortable with either of them. Good on you for creating this project and open sourcing it.

**Comment by nouveaupg** [comment]
First, I appreciate the kind words and am sorry for the somewhat delayed response. I am very happy with this app despite it not receiving the commercial success I might have hoped for. It is most likely the last app I write of this complexity, as I see software are a service being the future of commercially viable software from an independent developer's perspective. (I mean Apple and Microsoft both seem to be getting out of the business as well...) 

That being said I have a rewrite of the OpenPGP code in progress (this time in pure C), but far from complete. When I embarked on this project in 2014 OpenSSL was integrated into macOS very tightly but as of 10.7 it was deprecated and since removed. The idea was based on the premise that Objective-C/GNUstep was more compatible in practice than in theory and OpenSSL would be tightly integrated with both macOS and Linux for the foreseeable future, and possible to use with Windows. Since then Apple has promoted their own Crypto API which uses the same functionality (generally RSA/AES) with a completely different API, just as Microsoft had done before.

There is not much functional difference between 1.71, 1.72, and 1.73. It might be interesting to you that for App Store purposes, the integer build count is more important than version number.

1.71 is the App Store build without the 30-day trial/nag screen. 1.72 has the nag screen enabled, whereas 1.73 does not show it. When NouveauPG was back in the 1.5 era, there were still some known incompatibilities with other clients. Debugging these incompatibilities (which usually stemmed from something like unexpected handling of line endings) required me to basically set up the environment as close to the incompatible client's environment using a Virtual Machine, an older version of Windows, and what I could deduce from the version string of a message as the offending client. I can't see enough of a benefit at this time with Apple's rating system of releasing another version. I don't have much of an incentive to pull a Telegram (encrypted communication software of choice for Islamic terrorists) and scam the review system to skew the negative bias.
